[book]
authors = ["xzntrc#0001","Soda#4138"]
language = "en"
multilingual = false
src = "src"
title = "TempleOS Simplified"

[build]
# Follow gh pages convention:
build-dir = "./docs"

[output.html]
preferred-dark-theme = "ayu"
git-repo-url = "https://github.com/xzntrc/TOS"
edit-url-template = "https://github.com/xzntrc/TOS/edit/main/{path}"

[output.html.print]
enable = true
page-break = true

[output.html.redirect]
"/discord.html" = "https://discord.gg/Epu3WxjaP7"