[book]
authors = ["xzntrc#0001","Soda#4138"]
language = "en"
multilingual = false
src = "src"
title = "TempleOS Simplified"
description = "Learn TempleOS the easy way"

[build]
# Follow gh pages convention:
build-dir = "./docs"

[output.html]
preferred-dark-theme = "ayu"